import numpy as np

from ..base import CalibrationABC
from ..util import pfactor, rfactor
from ...doe import LHS


class SUFI2(CalibrationABC):
    """
    Sequential Uncertainty Fitting version 2.

    This implementation supports both a single supplied sample set and an
    iterative mode where new parameter samples are generated by LHS within
    updated bounds.

    Examples:
        >>> from UQPyL.calibration import SUFI2
        >>> sufi2 = SUFI2(maxIters=3, nSamples=32, metric="rmse", verboseFlag=False)
        >>> result = sufi2.run(problem, eliteSize=8, seed=123)
        >>> print(result.diagnostics["updatedLb"])

    References:
        [1] K. Abbaspour, S. Johnson, and M. van Genuchten, Estimating
            uncertain flow and transport parameters using a sequential
            uncertainty fitting procedure, Vadose Zone Journal, 3(4):1340-1352, 2004.

    Notes:
        - `pfactor` and `rfactor` are computed from the elite sample set.
        - In iterative mode, the current parameter bounds are updated by the
          elite min/max values and used to generate the next LHS sample set.
    """

    name = "SUFI2"

    def __init__(
        self,
        verboseFlag: bool = False,
        verboseFreq: int = 1,
        saveFlag: bool = False,
        logFlag: bool = False,
        maxIters: int = 1,
        nSamples: int | None = None,
        metric="rmse",
    ):
        super().__init__(
            verboseFlag=verboseFlag,
            verboseFreq=verboseFreq,
            saveFlag=saveFlag,
            logFlag=logFlag,
            metric=metric,
        )
        self.set("maxIters", maxIters)
        self.set("nSamples", nSamples)

    def _runCore(self, problem, X=None, eliteSize: int = 5, seed: int | None = None):
        """
        Run SUFI2 in one-shot or iterative mode.

        Args:
            problem: `ModelProblem` instance.
            X: Optional externally provided sample matrix. If omitted,
                `nSamples` must be configured and samples are generated
                internally by LHS.
            eliteSize: Number of elite samples retained each iteration.
            seed: Optional seed used when samples are generated internally.
        """
        maxIters = self.get("maxIters")
        nSamples = self.get("nSamples")

        lb_cur = np.asarray(problem.lb).reshape(-1)
        ub_cur = np.asarray(problem.ub).reshape(-1)
        last = None

        for iterIdx in range(maxIters):
            if X is None:
                if nSamples is None:
                    raise ValueError("nSamples must be provided when SUFI2 samples internally.")
                work_problem = self._makeSamplingProblem(problem, lb_cur, ub_cur)
                sampler = LHS()
                iter_seed = None if seed is None else int(seed + iterIdx)
                X_cur = sampler.sample(work_problem, nSamples, seed=iter_seed)
            else:
                X_cur = np.atleast_2d(X).astype(float, copy=False)

            last = self._runOneIteration(X_cur, eliteSize=eliteSize)
            lb_cur = last["updatedLb"]
            ub_cur = last["updatedUb"]

            self.state.history.metricsHistory.append(
                {
                    "iter": iterIdx + 1,
                    "pfactor": float(last["pfactor"]),
                    "rfactor": float(last["rfactor"]),
                    "updatedLb": last["updatedLb"].copy(),
                    "updatedUb": last["updatedUb"].copy(),
                }
            )

            if X is not None:
                break

        self.recordBest(last["bestDecs"], last["bestSim"])
        self.recordPosterior(last["X"], last["simFull"])
        self.recordElite(last["eliteDecs"], last["eliteSims"])
        self.state.diagnostics["scores"] = last["scores"].copy()
        self.state.diagnostics["eliteMask"] = last["eliteMask"].copy()
        self.state.diagnostics["updatedLb"] = last["updatedLb"].copy()
        self.state.diagnostics["updatedUb"] = last["updatedUb"].copy()
        self.state.diagnostics["pfactor"] = float(last["pfactor"])
        self.state.diagnostics["rfactor"] = float(last["rfactor"])
        self.state.diagnostics["eliteScores"] = last["eliteScores"].copy()
        self.state.diagnostics["ppuLower"] = last["ppuLower"].copy()
        self.state.diagnostics["ppuUpper"] = last["ppuUpper"].copy()

    def _runOneIteration(self, X, eliteSize: int = 5):
        """
        Execute one SUFI2 iteration on a given sample set.

        Args:
            X: Sample matrix with shape `(n_samples, n_input)`.
            eliteSize: Number of elite samples to keep.

        Returns:
            dict: Iteration diagnostics and updated bounds.
        """
        X = np.atleast_2d(X).astype(float, copy=False)
        sim_full = self.evaluate(X, validOnly=False)
        scores = self.score(sim_full)
        normalized = self.normalizedScore(sim_full)
        obs_valid = self.getValidObs().astype(float, copy=False)
        order = np.argsort(normalized)
        eliteSize = int(eliteSize)

        if eliteSize <= 0 or eliteSize > X.shape[0]:
            raise ValueError("eliteSize must be between 1 and n_samples.")

        eliteIdx = order[:eliteSize]
        eliteMask = np.zeros(X.shape[0], dtype=bool)
        eliteMask[eliteIdx] = True

        X_elite = X[eliteIdx]
        sim_elite_full = sim_full[eliteIdx]
        sim_elite_valid = self.problem.flattenSim(self.problem.simFunc(X_elite))[:, self.getValidMask()]
        scores_elite = scores[eliteIdx]

        bestIdx = int(order[0])
        bestDecs = X[bestIdx:bestIdx + 1].copy()
        bestSim = sim_full[bestIdx:bestIdx + 1].copy()

        updatedLb = np.min(X_elite, axis=0)
        updatedUb = np.max(X_elite, axis=0)

        ppuLower = np.quantile(sim_elite_valid, 0.025, axis=0)
        ppuUpper = np.quantile(sim_elite_valid, 0.975, axis=0)
        pfactorValue = pfactor(obs_valid, ppuLower, ppuUpper)
        rfactorValue = rfactor(obs_valid, ppuLower, ppuUpper)

        return {
            "X": X.copy(),
            "simFull": sim_full.copy(),
            "scores": scores.copy(),
            "eliteMask": eliteMask.copy(),
            "updatedLb": updatedLb.copy(),
            "updatedUb": updatedUb.copy(),
            "pfactor": pfactorValue,
            "rfactor": rfactorValue,
            "eliteDecs": X_elite.copy(),
            "eliteSims": sim_elite_full.copy(),
            "eliteScores": scores_elite.copy(),
            "ppuLower": ppuLower.copy(),
            "ppuUpper": ppuUpper.copy(),
            "bestDecs": bestDecs,
            "bestSim": bestSim,
        }

    def _makeSamplingProblem(self, problem, lb, ub):
        from ...problem import Problem

        return Problem(
            nInput=problem.nInput,
            nObj=1,
            lb=list(np.asarray(lb).reshape(-1)),
            ub=list(np.asarray(ub).reshape(-1)),
            objFunc=lambda X: np.zeros((np.atleast_2d(X).shape[0], 1)),
        )
