version: 2

# 设置构建环境
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# 使用 MkDocs 构建
mkdocs:
  configuration: mkdocs.yml

# 配置 Python 依赖并安装 MkDocs Material 主题
python:
  install:
    - method: pip
      requirements: docs-requirements.txt  # 使用 docs-requirements.txt 文件