site_name: UQPyL
theme:
  name: material
  palette:
    scheme: light
  code:
  highlight_theme: monokai
  features:
    - navigation.indexes

nav:
  - Introduction: 'index.md'
  - Quick Start: 'quick_start.md'
  - Tutorial:
      - Overview: 'overview.md'
      - Problem: 'problems.md'
      - Design of Experiment: 'design_of_experiment.md'
  - Example Collections: 'examples.md'
  - API Reference: 'api_reference.md'
  - ChangLog: 'chang_log.md'

extra_css:
  - css/nav_.css
  - css/head_.css
  - css/content_.css
  
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - js/nav-scroll.js

site_url: https://UQPyL.readthedocs.io/
repo_url: https://github.com/smasky/UQPyL

use_directory_urls: false

extra:
  static_path: docs