site_name: UQPyL
theme:
  name: material
nav:
  - Introduction: introduction.md
  - Quick Start: quick_start.md
  - Tutorial: tutorial.md
  - Examples Collection: examples.md
  - API Reference: api_reference.md
  - ChangLog: chang_log.md

extra_css:
  - css/nav_.css
  - css/head_.css

site_url: https://UQPyL.readthedocs.io/
repo_url: https://github.com/smasky/UQPyL