# Differential Evolution <Single>

import numpy as np

from typing import Optional

from ..base import AlgorithmABC
from ..population import Population
from ..core.constraint import betterMask, calcConstraintViolation
from ..core.tournament import tourSelect


class DE(AlgorithmABC):
    """
    Single-objective differential evolution.
    """
    
    name = "DE"
    alg_type = "EA"
    
    def __init__(self, cr: float = 0.9, f: float = 0.5,
                 nPop: int = 50,
                 maxFEs: int = 50000, 
                 maxIters: int = 1000, 
                 maxTolerates: int = 1000, tolerate: float = 1e-6, 
                 verboseFlag: bool = True, verboseFreq: int = 10, logFlag: bool = False, saveFlag: bool = True,
                 saveFreq: int = 100):
        """
        Initialize the algorithm.

        :param cr: Crossover probability.
        :param f: Differential weight.
        :param nPop: Population size.
        :param maxFEs: Maximum number of function evaluations.
        :param maxIters: Maximum number of iterations.
        :param maxTolerates: Maximum tolerated non-improving iterations.
        :param tolerate: Improvement tolerance.
        :param verboseFlag: Whether to print terminal output.
        :param verboseFreq: Summary output frequency.
        :param logFlag: Whether to save full text logs.
        :param saveFlag: Whether to save sqlite results.
        :param saveFreq: Snapshot save frequency.
        """
        
        super().__init__(maxFEs, maxIters, maxTolerates, 
                            tolerate, verboseFlag, verboseFreq, logFlag, saveFlag, saveFreq)
        
        # Set user-defined parameters
        self.setParaVal('cr', cr)
        self.setParaVal('f', f)
        self.setParaVal('nPop', nPop)
        
    def run(self, problem, seed: Optional[int] = None):
        """
        Run the algorithm on the given problem.

        :param problem: Problem instance.
        :param seed: Random seed.
        :return OptResult: Final optimization result.
        """
        # setup algorithm
        self.setup(problem, seed)
        
        # Parameter Setting
        cr, f = self.getParaVal('cr', 'f')
        nPop = self.getParaVal('nPop')
        
        # Population Generation
        pop = self.initPop(nPop)
        self.update(pop)
        
        # Iterative process
        while self.checkTermination(pop):
            
            # Select mating pool using tournament selection
            cv = calcConstraintViolation(pop.cons, pop.conWgt)
            feasible = np.zeros((len(pop), 1), dtype=float) if cv is None else (cv > 0).astype(float).reshape(-1, 1)
            violation = np.zeros((len(pop), 1), dtype=float) if cv is None else cv.reshape(-1, 1)
            matingIdx = tourSelect(2, len(pop)*2, feasible, violation, pop.objs)
            matingPool = pop[matingIdx]
            
            # Generate offspring using differential evolution operations
            offspringDecs = self._deOperator(pop.decs, matingPool.decs[:len(pop)], matingPool.decs[len(pop):], cr, f)
            offspring = Population(offspringDecs)
            
            # Evaluate the offspring
            self.evaluate(offspring)
            
            # Replace inferior individuals in the population with better offspring
            idx = betterMask(offspring.objs, offspring.cons, pop.objs, pop.cons, pop.conWgt)
            pop.replace(idx, offspring[idx])
            self.update(pop)
                    
        # Return the final result
        return self.finalize()
            
    def _deOperator(self, popDecs1, popDecs2, popDecs3, cr, f):
        """
        Perform differential evolution operations to generate offspring.

        :param popDecs1: First population.
        :param popDecs2: Second population.
        :param popDecs3: Third population.
        :param cr: Crossover probability.
        :param f: Differential weight.

        :return Population: New population generated by differential evolution.
        """
        
        N, D = len(popDecs1), len(popDecs1[0])
        
        # Differential Evolution operation
        sita = np.random.random((N, D)) < cr
        offspringDecs = np.copy(popDecs1)
        offspringDecs[sita] = popDecs1[sita] + (popDecs2[sita] - popDecs3[sita]) * f
        
        np.clip(offspringDecs, self.problem.lb, self.problem.ub, out=offspringDecs)
        
        return offspringDecs
